import './globals.css'
import type { Metadata } from 'next'
import { Inter,Roboto } from 'next/font/google'
import Navbar from './Navbar'
import localFont from 'next/font/local'
import { Suspense } from 'react'
import AuthProvider from './auth/Provider'

const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['400','500']
});

const poppins = localFont({
  src: '../public/fonts/BigParty4Blue-2575.woff',
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={poppins.variable}>
      <AuthProvider>
        <Navbar/>
        <main>
            {children}
        </main>  
      </AuthProvider>
      </body>
    </html>
  )
}
